#!/bin/bash

sudo apt-get install -y apt-utils
sudo apt-get install -y dialog
sudo apt update
sudo apt upgrade -y


# Baixa o script
curl -sSL https://github.com/EduardoCassemiroCWB/install_systens/main/SetupOrion -o SetupOrion


# Verifica se o download foi bem-sucedido
if [ $? -eq 0 ]; then
    # Executa o script baixado
    chmod +x SetupOrion
    ./SetupOrion
else
    echo "Falha ao baixar o script SetupOrion"
fi

sudo apt update
sudo apt upgrade -y

clear
rm SetupOrion
