#!/bin/bash

sudo apt-get install -y apt-utils
sudo apt-get install -y dialog
sudo apt update
sudo apt upgrade -y


# Baixa o script
curl -sSL https://raw.githubusercontent.com/EduardoCassemiroCWB/install_systens/main/SetupOrion -o SetupOrion






sudo apt update
sudo apt upgrade -y

clear
rm SetupOrion
